package problemaTRES;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MARAUD
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreGrande = new javax.swing.JLabel();
        agregarboton = new javax.swing.JButton();
        eliminarboton = new javax.swing.JButton();
        consultarboton = new javax.swing.JButton();
        salirboton = new javax.swing.JButton();
        imagenfondoprin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empresa ProblemaTRES");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreGrande.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        NombreGrande.setText("ProblemaTRES");
        getContentPane().add(NombreGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 330, 60));

        agregarboton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/botonp.png"))); // NOI18N
        agregarboton.setContentAreaFilled(false);
        agregarboton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/botonpX.png"))); // NOI18N
        agregarboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarbotonActionPerformed(evt);
            }
        });
        getContentPane().add(agregarboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 150, 50));

        eliminarboton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/botone.png"))); // NOI18N
        eliminarboton.setContentAreaFilled(false);
        eliminarboton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/botoneX.png"))); // NOI18N
        eliminarboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarbotonActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 150, 50));

        consultarboton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/botonc.png"))); // NOI18N
        consultarboton.setContentAreaFilled(false);
        consultarboton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/botoncX.png"))); // NOI18N
        consultarboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarbotonActionPerformed(evt);
            }
        });
        getContentPane().add(consultarboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 150, 50));

        salirboton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/botonS.png"))); // NOI18N
        salirboton.setContentAreaFilled(false);
        salirboton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/botonSX.png"))); // NOI18N
        salirboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirbotonActionPerformed(evt);
            }
        });
        getContentPane().add(salirboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 150, 50));

        imagenfondoprin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/principal.png"))); // NOI18N
        imagenfondoprin.setText("jLabel1");
        getContentPane().add(imagenfondoprin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirbotonActionPerformed
        login ventlogin = new login();
        ventlogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirbotonActionPerformed

    private void agregarbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarbotonActionPerformed
        agregardatos ventagregar = new agregardatos();
        ventagregar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agregarbotonActionPerformed

    private void eliminarbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarbotonActionPerformed
        elimdatos ventelim = new elimdatos();
        ventelim.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_eliminarbotonActionPerformed

    private void consultarbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarbotonActionPerformed
        consultdatos ventcont = new consultdatos();
        ventcont.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consultarbotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NombreGrande;
    private javax.swing.JButton agregarboton;
    private javax.swing.JButton consultarboton;
    private javax.swing.JButton eliminarboton;
    private javax.swing.JLabel imagenfondoprin;
    private javax.swing.JButton salirboton;
    // End of variables declaration//GEN-END:variables
}
